Rewrite prod-restore: fix import PG >= 11, faster too

diff --git a/bin/restore-prod-dump b/bin/restore-prod-dump
--- a/bin/restore-prod-dump
+++ b/bin/restore-prod-dump
@@ -1,10 +1,29 @@
-set -eux
+#!/usr/bin/env bash
 
-file=${FILE:-tmp/db_production.pgbin}
-export RAILS_ENV=development
+set -e
+
+FILE=${FILE:-tmp/db_production.pgbin}
+RAILS_ENV=development
 bundle exec rake db:environment:set
-bundle exec rake db:pg:terminate_connections
-bundle exec rake db:drop db:create
-bundle exec rake db:pg:structure_and_data:restore FILE=$file
+DBCONFIG=$(bundle exec rails runner "print(Rails.configuration.database_configuration[Rails.env].to_json) & STDOUT.flush")
+PGDATABASE=$(echo $DBCONFIG | jq -r .database)
+PGPORT=$(echo $DBCONFIG | jq -r .port)
+PGUSER=$(echo $DBCONFIG | jq -r .username)
+PGPASSWORD=$(echo $DBCONFIG | jq -r .password)
+J=$(ruby -e "require 'etc'; print((Etc.nprocessors/2.0).ceil) & STDOUT.flush")
+echo "PGPASSWORD=$PGDATABASE"
+echo "PGPORT=$PGPORT"
+echo "PGUSER=$PGUSER"
+echo "PGPASSWORD=$PGPASSWORD"
+echo "J=$J"
+# echo "ENTER to continue; abort with CTRL-C"
+# read
+psql -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$PGDATABASE' AND pid <> pg_backend_pid();"
+psql -c "DROP DATABASE IF EXISTS $PGDATABASE"
+psql -c "CREATE DATABASE $PGDATABASE"
+# this is required to restore dumps from PG <= 10 into PG >= 11
+# TODO it might cause problems on dups from PG >= 11
+psql -d $PGDATABASE -c "DROP SCHEMA IF EXISTS \"public\";"
+pg_restore --disable-triggers -j $J -x -O -d $PGDATABASE $FILE
 bundle exec rake db:migrate
-bundle exec rails runner "ApplicationRecord.connection.execute \"UPDATE settings SET external_base_url = 'http://localhost:3000'\""
+psql -d $PGDATABASE -c "UPDATE settings SET external_base_url = 'http://localhost:3000'"
